BeginTranslation(en_us, "English (US)")
    Translation(esp.player,				             "Player ESP")
    Translation(esp.player.showhealth,         "Show Health")
    Translation(esp.player.showarmor,          "Show Armor")
    Translation(esp.player.showmoney,          "Show Money")
    Translation(esp.player.showweapon,         "Show Weapon")
    Translation(esp.player.showclips,          "Show Clips")
    Translation(esp.player.drawbox,            "Draw Box")
    Translation(esp.player.showradarspotted,   "Show Radar Spotted")
    Translation(esp.player.drawglow,           "Draw Glow")

    Translation(esp.world,				             "World ESP")

    Translation(misc,				                   "Misc")

    Translation(credits,				               "Credits")

    Translation(menu.setting,			             "Setting")
    Translation(menu.setting.format.current,   "Current Setting: {0}")
    Translation(menu.setting.new,              "New Setting...")
    Translation(menu.setting.load,             "Load Setting...")
    Translation(menu.setting.saveall,          "Save All...")
    Translation(menu.setting.format.rename,    "Rename {0} As...")
    Translation(menu.setting.format.duplicate, "Duplicate {0} As...")
    Translation(menu.setting.format.remove,    "Remove {0} As...")
    Translation(menu.setting.set.default,      "Set Default...")
	
    Translation(menu.language,				         "Language")
EndTranslation()