BeginTranslation(zh_hk, u8"中文 (香港)")

    Translation(esp.player,					           u8"玩家透視")
    Translation(esp.player.showhealth,		     u8"顯示血量")
    Translation(esp.player.showarmor,		       u8"顯示裝甲量")
    Translation(esp.player.showmoney,		       u8"顯示金錢")
    Translation(esp.player.showweapon,		     u8"顯示武器")
    Translation(esp.player.showclips,		       u8"顯示彈夾量")
    Translation(esp.player.drawbox,			       u8"顯示透視方框")
    Translation(esp.player.showradarspotted,   u8"雷達顯示")

    Translation(menu.setting,				           u8"設定")
    Translation(menu.setting.format.current,   u8"目前使用設定: {0}")
    Translation(menu.setting.new,              u8"建立新設定...")
    Translation(menu.setting.load,             u8"讀取設定...")
    Translation(menu.setting.saveall,          u8"保存所有設定...")
    Translation(menu.setting.format.rename,    u8"重命名設定 {0}...")
    Translation(menu.setting.format.duplicate, u8"複製設定 {0}...")
    Translation(menu.setting.format.remove,    u8"移除設定 {0}...")
    Translation(menu.setting.set.default,      u8"選擇默認設定...")

    Translation(menu.language,				         u8"語言")

    Translation(credits,				               u8"鳴謝")

EndTranslation()